spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: 'Apple에서 생성한 Service ID'
            client-secret: 'Apple에서 생성한 Secret'
            authorization-grant-type: authorization_code
            redirect-uri: "https://도메인/login/oauth2/code/apple"  # 애플 로그인 후 리디렉션 URL
            clientAuthenticationMethod: POST
            clientName: Apple
            scope:
              - name
              - email              # Apple에서 요청할 권한 (email과 name)
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/kopring}
    username: dev
    password: 10041004
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    show-sql: true
    generate-ddl: true

app:
  auth:
    tokenSecret: 9a1c7805bb074f31f9b36fa510d0c743a557aa44f9b5b1cd6dbb7f8905b067c8
    tokenExpiry: 7776000000 #3달
  oauth2:
    authorizedRedirectUris:
      - https://도메인/login/oauth2/code/apple

key:
  file:
    path: ${KEY_PATH:classpath:keyfiles/}