spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            clientId: { 애플로부터 받은clientId }
            clientSecret: { 애플로부터 받은 key 파일 }.p8
            redirectUri: "${backend-rooturl-origin}/login/oauth2/code/apple"
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Apple
            scope:
              - name
              - email

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/kopring}
    username: dev
    password: 10041004
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    show-sql: true
    generate-ddl: true

jwt :
  access :
    key : 9a1c7805bb074f31f9b36fa510d0c743a557aa44f9b5b1cd6dbb7f8905b067c8
    validtime : 604800000 #7일